export const config = {
  developer: { name: "Oumar", fullName: "Oumar Ammar", title: "Software Engineer | Full-Stack Developer", description: "Software Engineer turning complex ideas into reliable digital products, with a specialization in Data Engineering." },
  social: { github: "oumar969", email: "oammar198@gmail.com", location: "Denmark" },
  about: { title: "About Me", description: "I am a Software Engineer from VIA University College, specializing in Data Engineering. I build full-stack web and mobile applications, from user interfaces to backend services, APIs and databases. My data work includes Python, SQL, ETL pipelines, data modelling and Power BI. Across both, I focus on clean architecture and reliable products that are easy to use." },
  experiences: [
    { position: "Frontend Developer Intern", company: "TinyMobileRobots", period: "2024 - 2025", location: "Malling, Denmark", description: "Built customer-specific sports-field templates and interactive configuration features in an international product team.", responsibilities: ["Implemented customer-specific field templates", "Collaborated with product and backend teams", "Debugged and improved production features"], technologies: ["JavaScript", "Cordova", "jQuery", "REST APIs"] },
    { position: "Software Engineering", company: "VIA University College", period: "2022 - 2026", location: "Horsens, Denmark", description: "Completed seven industry-focused semester projects and graduated as a Software Engineer specializing in Data Engineering.", responsibilities: ["Bachelor project grade: 12", "Built full-stack and real-time systems", "Worked in cross-functional project teams"], technologies: ["TypeScript", "C#", ".NET", "Java", "Python", "SQL"] },
    { position: "Full-Stack Developer", company: "Client & Personal Projects", period: "2023 - Present", location: "Denmark", description: "Designing, building and deploying complete web and mobile products for real users and businesses.", responsibilities: ["Shipped production web applications", "Built mobile and PWA products", "Implemented auth, booking and real-time sync"], technologies: ["React", "Next.js", "Node.js", "Flutter", "Firebase", "Docker"] }
  ],
  projects: [
    { id: 8, title: "NordicFlow", category: "Cloud Data Platform", technologies: ".NET, React, Azure, Databricks, PySpark, Delta Lake, Terraform", image: "/images/nordicflow-overview.png", description: "Built to explore how scattered supply-chain events can become trustworthy insights, using secure ingestion, data-quality checks and structured cloud pipelines.", link: "/nordicflow.html" },
    { id: 1, title: "Rentop", category: "Client / Full-Stack", technologies: "Next.js, TypeScript, Booking System, Admin Dashboard, Invoicing, SEO", image: "/images/rentop.png", description: "Built for a Danish cleaning business to bring customer bookings, invoicing and daily administration into one place, reducing fragmented manual workflows.", link: "https://rentop.dk" },
    { id: 7, title: "AeroSight", category: "AI / Wind Energy", technologies: "Next.js, TypeScript, React, Tailwind CSS, Supabase, Resend", image: "/images/aerosight.png", description: "Built to bring wind-turbine inspection imagery and maintenance findings into one workflow, helping teams turn drone observations into actionable reports.", link: "https://github.com/oumar969/-AeroSight" },
    { id: 2, title: "Lumo", category: "Real-Time Mobile", technologies: "React Native, Firebase, Node.js, Turso", image: "/images/lumo-screenshots/lumo-home.png", description: "Built to give small groups a private shared space for live drawing, notes and collaboration, keeping ideas together and updates in sync.", link: "https://github.com/oumar969/Lumo-app" },
    { id: 3, title: "For Hinanden", category: "Community Platform", technologies: "Flutter, ASP.NET Core, PostgreSQL, Firebase", image: "/images/forhinanden-1.png", description: "Built to connect people who need everyday help with nearby volunteers, bringing matching, task coordination and real-time chat into one platform.", link: "https://github.com/Zenbax/for-hinanden-frontend" },
    { id: 4, title: "Padel Score", category: "Real-Time PWA", technologies: "Flutter, Firestore, Riverpod, PWA", image: "/images/padel-score.png", description: "Built to make padel scoring easy to track and share, with live spectator updates and a TV scoreboard that stays in sync with the match.", link: "https://padel-score-ab0b5.web.app" },
    { id: 5, title: "SmartCharger", category: "Clean Energy / Full-Stack", technologies: ".NET 8, React, TypeScript, ML.NET, SQLite, Docker", image: "/images/smartcharger.png", description: "Built to help Danish EV drivers find cheaper or greener charging windows using live electricity prices, carbon-intensity data and price forecasts.", link: "https://github.com/oumar969/SmartCharger" },
    { id: 6, title: "TimeTrack Pro", category: "Workforce Management", technologies: "React, Node.js, Express, PostgreSQL, JWT, Docker", image: "/images/timetrack-pro.png", description: "Built to simplify employee time tracking, replacing scattered records with secure clock-in, shift history and clear weekly reports.", link: "https://github.com/oumar969/timetrack-pro" }
  ],
  contact: { email: "oammar198@gmail.com", github: "https://github.com/oumar969", linkedin: "https://www.linkedin.com/in/omar-a-8a2491253/", twitter: "https://github.com/oumar969", facebook: "https://github.com/oumar969", instagram: "https://github.com/oumar969" },
  skills: {
    develop: { title: "SOFTWARE ENGINEER", description: "Reliable software with a Data Engineering specialization", details: "I build maintainable systems across backend, APIs and databases. My Data Engineering experience includes Python, SQL, ETL pipelines, dimensional modelling and Power BI.", tools: ["C#", ".NET", "Python", "SQL", "REST APIs", "ETL Pipelines", "PostgreSQL", "Power BI", "Docker", "Git"] },
    design: { title: "FULL-STACK", description: "Modern web & mobile applications", details: "Creating responsive products from interface to database using modern web and mobile technologies.", tools: ["React", "Next.js", "Node.js", "React Native", "Flutter", "Firebase", "Tailwind CSS", "Vercel", "Git"] }
  }
};
